### ISSUE TITLE
Discord Bot无法连接

### ISSUE THREAD

**Issue by SinonGame** [mrhso/LilyWhiteBot#6]
10月11日更新：
之前是由于配置错误，今天开始完全无法连接discord机器人，就是把proxyurl打开也没用，错误信息:
更改host:
`(node:6416) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
(node:6416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:6416) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.`
未更改host:
`(node:5948) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 140.238.3
5.210:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
(node:5948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:5948) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.`

**Comment by EarthMC-BE** [comment]
npm install的时候如下错误：
`C:\Users\visit\Downloads\LilyWhiteBot-master>npm install
npm WARN deprecated snekfetch@3.6.4: use node-fetch instead
npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN discord.js@11.5.1 requires a peer of bufferutil@^4.0.0 but none is inst
alled. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of erlpack@discordapp/erlpack but non
e is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of libsodium-wrappers@^0.7.3 but none
 is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of node-opus@^0.2.7 but none is insta
lled. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of opusscript@^0.0.6 but none is inst
alled. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of sodium@^2.0.3 but none is installe
d. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of @discordjs/uws@^10.149.0 but none
is installed. You must install peer dependencies yourself.
npm WARN lilywhitebot@1.3.1 No repository field.
npm WARN lilywhitebot@1.3.1 No license field.

added 111 packages from 152 contributors and audited 142 packages in 7.516s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details`

**Comment by mrhso** [comment]
proxy 那个我没写 Discord 的。现在内地 Discord 已经彻底 RST 了吗？

**Comment by mrhso** [comment]
如果确认内地已经彻底墙掉的话，我有空改改吧。

**Comment by SinonGame** [comment]
国内已经彻底完蛋了，改host也没用了，用dogfight360的反代无法连接，提示SSL不正确。另外建议增加一下图片互通发送功能，图片无法发送这个是真的难受

**Comment by SinonGame** [comment]
最好加一个本地代理，就是说本地有一个socks服务器，通过这个代理服务器连接discord

**Comment by SinonGame** [comment]
请尽快解决一下............

**Comment by SirnoChan** [comment]
要不乾脆弄個國外VPS吧

**Comment by SinonGame** [comment]
@SirnoChan 我现在直接就是挂的ss-tap全局代理，但是不是长久的方案啊，最好还是加一个代理的接口

**Comment by mrhso** [comment]
这个要是 discord.js 有代理接口就简单，但是它那文档死难读……

**Comment by SinonGame** [comment]
能不能让nodejs的所有流量走代理呢？
https://github.com/discordjs/discord.js/issues/3039
这个有没有用？
